
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 27 23:27:08 CDT 2017
//----------------------------------------------------

package ParsePkg;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RARROW = 33;
  public static final int DISPLAY = 37;
  public static final int UMINUS = 11;
  public static final int LPAREN = 4;
  public static final int GREATER = 19;
  public static final int INT = 38;
  public static final int MINUS = 10;
  public static final int RPAREN = 5;
  public static final int NOT = 21;
  public static final int SEMICOLON = 14;
  public static final int AND = 22;
  public static final int FUN = 40;
  public static final int OR = 23;
  public static final int BOOL = 39;
  public static final int COMMA = 9;
  public static final int DDOT = 8;
  public static final int FI = 29;
  public static final int DIV = 12;
  public static final int GEQ = 16;
  public static final int LESSER = 20;
  public static final int PLUS = 2;
  public static final int IF = 28;
  public static final int ID = 36;
  public static final int DOUBLARROW = 42;
  public static final int NUF = 41;
  public static final int EOF = 0;
  public static final int OD = 27;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int NUMBER = 35;
  public static final int NEQ = 18;
  public static final int EQ = 17;
  public static final int BOX = 34;
  public static final int LBRACK = 6;
  public static final int TIMES = 3;
  public static final int COLON = 13;
  public static final int SKIP = 31;
  public static final int RBRACK = 7;
  public static final int THEN = 30;
  public static final int LEQ = 15;
  public static final int LARROW = 32;
  public static final int FALSE = 25;
  public static final int DO = 26;
}

