
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 27 18:09:27 CDT 2017
//----------------------------------------------------

package ParsePkg;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int PLUS = 3;
  public static final int RPAREN = 6;
  public static final int LPAREN = 5;
  public static final int ID = 17;
  public static final int UNLESS = 15;
  public static final int DO = 14;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int NUMBER = 16;
  public static final int DIV = 12;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int DOT = 2;
  public static final int ASSIGN = 10;
  public static final int LEQ = 13;
  public static final int OUTPUT = 8;
  public static final int UMINUS = 7;
}

