
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 06 22:56:34 CST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RARROW = 32;
  public static final int DISPLAY = 36;
  public static final int LPAREN = 4;
  public static final int GREATER = 18;
  public static final int INT = 37;
  public static final int MINUS = 10;
  public static final int RPAREN = 5;
  public static final int NOT = 20;
  public static final int SEMICOLON = 13;
  public static final int AND = 21;
  public static final int RANGE = 8;
  public static final int FUN = 39;
  public static final int OR = 22;
  public static final int BOOL = 38;
  public static final int COMMA = 9;
  public static final int FI = 28;
  public static final int DIV = 11;
  public static final int GEQ = 15;
  public static final int LESSER = 19;
  public static final int PLUS = 2;
  public static final int IF = 27;
  public static final int ID = 35;
  public static final int DOUBLARROW = 41;
  public static final int NUF = 40;
  public static final int EOF = 0;
  public static final int OD = 26;
  public static final int TRUE = 23;
  public static final int error = 1;
  public static final int DOUBRARROW = 42;
  public static final int NUMBER = 34;
  public static final int NEQ = 17;
  public static final int EQ = 16;
  public static final int BOX = 33;
  public static final int LBRACK = 6;
  public static final int TIMES = 3;
  public static final int COLON = 12;
  public static final int SKIP = 30;
  public static final int RBRACK = 7;
  public static final int THEN = 29;
  public static final int LEQ = 14;
  public static final int LARROW = 31;
  public static final int FALSE = 24;
  public static final int DO = 25;
}

