
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 20 12:23:24 CST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RARROW = 31;
  public static final int DISPLAY = 35;
  public static final int LPAREN = 4;
  public static final int GREATER = 17;
  public static final int INT = 36;
  public static final int MINUS = 9;
  public static final int RPAREN = 5;
  public static final int NOT = 19;
  public static final int SEMICOLON = 12;
  public static final int AND = 20;
  public static final int FUN = 38;
  public static final int OR = 21;
  public static final int BOOL = 37;
  public static final int COMMA = 8;
  public static final int FI = 27;
  public static final int DIV = 10;
  public static final int GEQ = 14;
  public static final int LESSER = 18;
  public static final int PLUS = 2;
  public static final int IF = 26;
  public static final int ID = 34;
  public static final int DOUBLARROW = 40;
  public static final int NUF = 39;
  public static final int EOF = 0;
  public static final int OD = 25;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int DOUBRARROW = 41;
  public static final int NUMBER = 33;
  public static final int NEQ = 16;
  public static final int EQ = 15;
  public static final int BOX = 32;
  public static final int LBRACK = 6;
  public static final int TIMES = 3;
  public static final int COLON = 11;
  public static final int SKIP = 29;
  public static final int RBRACK = 7;
  public static final int THEN = 28;
  public static final int LEQ = 13;
  public static final int LARROW = 30;
  public static final int FALSE = 23;
  public static final int DO = 24;
}

